#!/bin/env python3
import csv
import getopt
import os
import sys
from rpkitracker import *

NB_BARS = 20
output_format = "md"
nb_topas = 10

opts, args = getopt.getopt(sys.argv[1:], 'ctn:')
for optname, optval in opts:
	if optname == '-c':
		output_format = "csv"
	elif optname == '-t':
		output_format = "topaslist"
	elif optname == '-n':
		nb_topas = int(optval)

out = list[Row]()
asn_ln_map = dict[str, str]()
route_map = dict[str, set[str]]()
rpki_enabled_set = set[str]()

with open(args[0]) as f:
	for line in f:
		r = line.split('\t')
		asn_ln_map[r[0].strip()] = r[1].strip()

with open(args[1]) as f:
	for line in f:
		r = line.split('\t')
		asn = r[0].strip()
		s = route_map.get(asn)
		route_map[asn] = set[str](r[1].split())

with open(args[2]) as f:
	for line in f:
		rpki_enabled_set.add(line.strip())

for asn, v in route_map.items():
	nb_total = len(v)
	if nb_total == 0:
		continue

	nb_rpki_enabled = 0
	for prefix in v:
		if prefix in rpki_enabled_set:
			nb_rpki_enabled += 1

	localname = asn_ln_map.get(asn, '')
	ratio = nb_rpki_enabled / nb_total
	nb_i = int(NB_BARS * ratio)
	nb_e = NB_BARS - nb_i
	element = Row(asn, localname, nb_rpki_enabled, nb_total, ratio)
	element.bars = '█' * nb_i + '▒' * nb_e

	out.append(element)

if output_format == 'md':
	out.sort(key = key_total_as_f, reverse = True)

	print(
'''| ASN | Name | RPKI | Total | % | Bars |
|-|-|-:|-:|-:|-|'''
		)
	for row in out:
		print(
			"| %s | %s | %d | %d | %.2f%% | %s |" %
			( row.asn, row.name, row.rpki_cnt, row.total_cnt, row.ratio * 100, row.bars ))
elif output_format == 'csv':
	fieldnames = [ 'ASN', 'Name', 'RPKI', 'Total', '%' ]

	out.sort(key = key_total_as_f, reverse = True)

	w = csv.writer(sys.stdout)
	w.writerow(fieldnames)
	for row in out:
		tpl = ( row.asn, row.name, row.rpki_cnt, row.total_cnt, row.ratio * 100, )
		w.writerow(tpl)
elif output_format == 'topaslist':
	for ra in out:
		rank = 0
		for rb in out:
			if ra.rpki_cnt < rb.rpki_cnt:
				rank += 1
		ra.rank = rank

	out.sort(key = key_rank_as_f, reverse = False)

	for row in out:
		if row.rank > nb_topas:
			break
		print(row.asn)
else:
	os.abort()
