#!/bin/bash
. common.sh

read_prefixes () {
	grep -Eoi '[a-f0-9.:]+/[0-9]{1,3}' | while read l
	do
		echo '!r'"$l"
	done
}

process_result () {
	local r

	while read -d '' r
	do
		if echo "$r" | grep -Eiqs '^rpki-ov-state:(\s+)?valid'; then
			echo "$r" |
				grep -Eoi 'route6?:(\s+)?[a-f0-9.:]+/[0-9]{1,3}' |
				sed -E 's/^route6?:(\s+)?//' |
				sort |
				uniq |
				head -n1
		fi
	done
}


read_prefixes | open_db | extract_answer | process_result
