#!/bin/bash
set -e
. common.sh

PIPE_NAME="$$.fifo.tmp"

if [ "$1" == "-6" ]; then
	Q_PREFIX='!6'
else
	Q_PREFIX='!g'
fi

read_aslist () {
	local asn

	while read asn
	do
		echo ${Q_PREFIX}${asn}
	done
}

output_filter () {
	local a
	local b

	while read -u 3 a && read -d '' b
	do
		printf '%-12s\t%s\n' "$a" "$b"
	done
}


set -o pipefail
read_aslist | open_db | extract_answer | output_filter
